# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: petal-note-service

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment:
    NOTES_TABLE: notes-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}"

resources:
  Resources:
    NoteTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          - AttributeName: NoteId
            KeyType: HASH
          - AttributeName: Title
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: NoteId
            AttributeType: S
          - AttributeName: Title
            AttributeType: S
          - AttributeName: Content
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.NOTES_TABLE}
        GlobalSecondaryIndexes:
          - IndexName: TitleContentIndex
            KeySchema:
              - AttributeName: Title
                KeyType: HASH
              - AttributeName: Content
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - NoteId
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

custom:
  defaultStage: dev
  profiles:
    dev: devProfile
    prod: prodProfile

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.query
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: query
          method: get
          cors: true
